### ISSUE TITLE
Wrong url link for Arduino IDE board package on README.md

### ISSUE THREAD

**Issue by desar** [redbear/nRF5x#1]
The following link on Getting Started section or README.md result to 404 page.
"Installing nRF52832 board package"
Wrong url: https://github.com/redbear/nRF52-Beta/blob/master/docs/Arduino_Board_Package_Installation_Guide.md

The path should be "nRF5x" I think?
https://github.com/redbear/nRF5x/blob/master/docs/Arduino_Board_Package_Installation_Guide.md

**Comment by Cheong2K** [comment]
Thank you for pointing out.
