### ISSUE TITLE
Ticker stops with softdevice running

### ISSUE THREAD

**Issue by lpercifield** [redbear/nRF5x#13]
Potentially related to: https://github.com/ARMmbed/mbed-os/issues/3857

Trying the BLE_SimplePeripheral example with the added Ticker_Task, the ticker callback stops being called almost immediately after startup. Is this potentially related to the ble.waitForEvent() sleep?

**Comment by ghost** [comment]
ble.waitForEvent isn't needed on mbed os 5.  Are you using 2.x?

**Comment by lpercifield** [comment]
Turns out it was an issue using the onRadioNotification implementation. Seems that the callback was interrupting much of my application and causing the ticker to stop. Closing for now.
