### ISSUE TITLE
missing file nRF52832_EraseChip.hex

### ISSUE THREAD

**Issue by ohagendorf** [redbear/nRF5x#4]
Hello @Cheong2K

at the end in your DAPLink_User_Guide.md, you are mentioning a possible download problem with the solution of programming the nRF52832_EraseChip.hex. I have this problem. Unfortunatly the file link is broken. And I can't try your solution.

**Comment by Cheong2K** [comment]
Hi, thanks for pointing out this, please check this firmware:
https://github.com/redbear/nRF5x/tree/master/test

**Comment by ohagendorf** [comment]
Thanks a lot.

I'm closing this.
