### ISSUE TITLE
Not able to program a generic (non-redbear) nRF52 board

### ISSUE THREAD

**Issue by Priyanshi1106** [redbear/nRF5x#45]
I am trying to program an nRF52 beacon to a BLE peripheral. 

I am not able to program the generic device. The code uploads without errors but does not run. I have successfully programmed a BLE Nano V1 using the same code.

**Comment by Dexter123193** [comment]
Hi,

Have you tried to pair BLE Nano with Pi 3b ?
I am facing timeout issues.

Regards.
